name: Test plugins

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: tests/.build/ysfx
          key: ysfx-${{ hashFiles('tests/run.sh') }}
      - run: sudo apt-get install -y nasm
      - run: tests/run.sh
      - run: python3 tools/build_site.py --check
